version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./master.Dockerfile
    working_dir: /root/playbooks
    volumes:
      - ./master/playbooks:/root/playbooks
      - ./master/config:/etc/ansible
    entrypoint: 
      - /bin/sh
      - -c
      - |
        tail -f /dev/null
      # ansible-playbook lamp.yml
    depends_on:
      - web
      - lb
    networks:
      - web
      - lb
  
  lb:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    ports: 
      - 8080:80
    networks:
      - lb

  web:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - web
      - lb


networks:
  web:
    driver: bridge
  lb:
    driver: bridge

